
theme: jekyll-theme-minimal

title: marunomi_
description: 音楽を聴くことが好きデス⭐︎
logo: img/icon.jpg

kramdown:
  input: GFM

plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag

github: [metadata]
repository: marunomi/marunomi.github.io
google_analytics: UA-164526787-1
